language: java
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V
script: mvn test -Dgpg.skip=true
jdk:
  - openjdk8
sudo: false

notifications:
  email: false
  slack:
    secure: MqnUy7Xzwa4eEi0DG4yKCRWJ9hC+WxtCre+l/ZFutBwJPVS/LstCIGK/YhRiqAT7gFBqXj/AKuDQy3AlaZNkhg9smGcTrE9H5TKds4r4fK8amHYrvleUg3MNtghSs7WajOnWqh4i9VTQ2w3/or1hyCBCzSLVo8usiwStwxMA3Pn/ENDOU7c1yw74i5BiU6fmxkNtRioyDP4RXUCvPdtn31xLta2wd18SleALfbpaH1DMFlqFgghepwvNarakWDlALUA+rYEUdm3hPGf86KL/CvDeABYYxry/x++5Oi+OESWKt0CuyRnVtiNnLObsUOIIx9jYdx03BT/pr4fXvrduh3rZMQcZ8K9FihJSMw3zgXLc8Rrt/dezZPE3T5QOy8xIERQTrHSp6nuzLq/tuu7JFUwiMAXXmDlBWqr2MirtnUDZV8ysL6KvDiQ5U7J9Sihq42ong1yYA5W0Fc1xL2A3gf5G3BiwsJ7+luWR7PEBHQPseb49XMHETX7F5CuXS9svc9SSlPG/uPCpWPlBcLGIQ8EQ+ac4xJgKtxxQgR12vLqmOmueZCMeqKCI/nO17t3fH6BPBxO6NNqEW6UDwtvW303Li/VnjQjNW/1g+NlOBpvJNhYH2T/Q32BtdoEX6MUOh30yY+EU8e+broHH10bCVLxJ0d+JXTAC5frq3iyypTQ=
